
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rivaldo;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author rivaldz
 */
public class Transaksi extends javax.swing.JFrame {
	int i = 0;
	Item barang;
	ItemPenjualan penjualan = new ItemPenjualan(); //objek class ItemPenjualan 
	private DefaultTableModel tabel = new DefaultTableModel(); //memanggil method default table 
	boolean enable = true;
	/**
	 * Creates new form Transaksi
	 */
	public Transaksi() {
		initComponents();
		fillComboBarang(); //pemanggilan method untuk menjalankan perintah jComboBox 
		tblBarang.setModel(penjualan.getTabel());
		buttonTogle();
	}
	private void buttonTogle(){ //method untuk disable enable ui java
		addButton.setEnabled(false);
		itemComboBox.setEnabled(false);
		itemValue.setEnabled(false);
		removeTitle.setEnabled(false);
		tblBarang.setEnabled(false);
		SaveButton.setEnabled(false);
		CancelButton.setEnabled(false);
		codeValue.setEnabled(enable);
	}
	
    private void fillComboBarang(){ //method untuk mengisi jComboBox
	Item item1 = new Item("Susu", 10000);
	Item item2 = new Item("Kopi", 11000);
	Item item3 = new Item("Gula", 12000);
	//Item item4 = new Item("Gula", 12000);
		
	itemComboBox.addItem(item1);
	itemComboBox.addItem(item2);
	itemComboBox.addItem(item3);
	//itemComboBox.addItem(item4);
    }
		
	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                codeValue = new javax.swing.JTextField();
                newButton = new javax.swing.JButton();
                itemComboBox = new javax.swing.JComboBox();
                itemValue = new javax.swing.JTextField();
                addButton = new javax.swing.JButton();
                removeTitle = new javax.swing.JButton();
                SaveButton = new javax.swing.JButton();
                CancelButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblBarang = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Transaksi");

                jLabel1.setText("Code");

                jLabel2.setText("Item");

                codeValue.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                codeValueActionPerformed(evt);
                        }
                });

                newButton.setText("New");
                newButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                newButtonActionPerformed(evt);
                        }
                });

                itemComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                itemComboBoxActionPerformed(evt);
                        }
                });

                itemValue.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                itemValueActionPerformed(evt);
                        }
                });

                addButton.setText("Add");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });

                removeTitle.setText("Remove");
                removeTitle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                removeTitleActionPerformed(evt);
                        }
                });

                SaveButton.setText("Save");
                SaveButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SaveButtonActionPerformed(evt);
                        }
                });

                CancelButton.setText("Cancel");
                CancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CancelButtonActionPerformed(evt);
                        }
                });

                tblBarang.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "Nama", "Harga", "Jumlah"
                        }
                ));
                jScrollPane1.setViewportView(tblBarang);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(itemValue, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                                        .addComponent(codeValue, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(97, 97, 97)
                                                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(codeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newButton))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(itemValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(removeTitle)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CancelButton)
                                        .addComponent(SaveButton))
                                .addGap(33, 33, 33))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void codeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeValueActionPerformed
                // TODO add your handling code here:
		
        }//GEN-LAST:event_codeValueActionPerformed

        private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed

                // TODO add your handling code here:
		if (newButton.getText().equals("New")) {//apabila di tekan new maka button di bawahnya akan muncul 
			addButton.setEnabled(enable);
			codeValue.setEnabled(false);			
			itemComboBox.setEnabled(enable);
			itemValue.setEnabled(enable);
			newButton.setEnabled(false);
		}
		
		i++;
		Date date = new Date(); //instansiasi object untuk date
		SimpleDateFormat date1 = new SimpleDateFormat("yyMMdd"); //memanggil tanggal dari object (menentukan format)
		String tanggal = date1.format(date.getTime());//memanggil tanggal dengan format yang telah di buat 
		codeValue.setText(tanggal + String.format("%02d",i));//me set ke gui 
		
        }//GEN-LAST:event_newButtonActionPerformed

        private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
                // TODO add your handling code here:
		barang = (Item)itemComboBox.getSelectedItem();//memanggil item di tampilkan di combo box
        }//GEN-LAST:event_itemComboBoxActionPerformed

        private void itemValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemValueActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_itemValueActionPerformed

        private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
                // TODO add your handling code here;
		
		String isi = itemValue.getText();//memanggil text yang ada di kolom itemvalue
		if (isi.equals("")) {//cek apakah kolom sudah terisi 
			JOptionPane.showMessageDialog(null, "masukan jumlah di kolom kiri Add","Mohon Perhatian", JOptionPane.WARNING_MESSAGE);
		} else { 
		
			removeTitle.setEnabled(enable);
			tblBarang.setEnabled(enable);
			SaveButton.setEnabled(enable);
			CancelButton.setEnabled(enable);
			
			DefaultTableModel model =(DefaultTableModel)tblBarang.getModel();
			
			String[] data = new String[3];			
			data[0]=barang.getNamaBarang();	//memasukan nama barang dari class item ke indek table 
			data[1]=String.valueOf(barang.getHarga()); //memasukan harga barang dari class item ke indek table 
			data[2]=itemValue.getText(); //memasukan jumlah item  dari class item ke indek table 
			penjualan.getTabel().addRow(data); //memasukan semua index data ke table row 
			
		}
        
        }//GEN-LAST:event_addButtonActionPerformed

        private void removeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTitleActionPerformed
                // TODO add your handling code here:
		
		penjualan.getTabel().removeRow(tblBarang.getSelectedRow()); //mengahapus data yang dipilih user 
		
        }//GEN-LAST:event_removeTitleActionPerformed

        private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
                // TODO add your handling code he
		double harga, jumlah = 0 ;
		int qty = 0 ;
		
		harga = barang.getHarga();  //menampilkan dan memanggil method perhitungan dan tampilan nama dari class itempenjualan 
		qty = Integer.parseInt(itemValue.getText());		
		JOptionPane.showMessageDialog(null, "Kode : " + codeValue.getText() + "\n" + "Daftar Belanja: \n" + "Nama Barang " +penjualan.showSave() + "\n" + "Total " +penjualan.countSubtotal());
		DefaultTableModel model =(DefaultTableModel)tblBarang.getModel();
		while (model.getRowCount() > 0) { //me set ulang tabel ke kosong setelah di save 
			for (int j = 0; j < model.getRowCount(); j++) {
				model.removeRow(j);
			}
		}
		//codeValue.setText(null);
		itemValue.setText(null);
		addButton.setEnabled(false);
		codeValue.setEnabled(false);			
		itemComboBox.setEnabled(false);
		itemValue.setEnabled(false);
		newButton.setEnabled(enable);
		codeValue.setEnabled(enable);
        }//GEN-LAST:event_SaveButtonActionPerformed

        private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
                // TODO add your handling code here:
		DefaultTableModel model =(DefaultTableModel)tblBarang.getModel();
		
		while (model.getRowCount() > 0) { //mengkosongkan tabel apabila user clik cancel 
			for (int j = 0; j < model.getRowCount(); j++) {
				model.removeRow(j);
			}
		}
		//codeValue.setText(null);
		itemValue.setText(null); //mengkosongkan isi masukan jumlah item yang di masukan oleh user 
		
        }//GEN-LAST:event_CancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Transaksi().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton CancelButton;
        private javax.swing.JButton SaveButton;
        private javax.swing.JButton addButton;
        private javax.swing.JTextField codeValue;
        private javax.swing.JComboBox itemComboBox;
        private javax.swing.JTextField itemValue;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton newButton;
        private javax.swing.JButton removeTitle;
        private javax.swing.JTable tblBarang;
        // End of variables declaration//GEN-END:variables
}
